CREATE TABLE IF NOT EXISTS DEPARTMENT(

EMPLOYEE_ID TEXT,

NAME TEXT,

DEPARTMENT_ID TEXT,

MANAGER_ID TEXT,

SALARY REAL

);

INSERT INTO DEPARTMENT (EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY) VALUES

('E001', 'Alice Smith', 'D001', 'M001', 75000),

('E002', 'Bob Johnson', 'D002', 'M002', 60000),

('E003', 'Charlie Brown', 'D001', 'M001', 80000),

('E004', 'David Wilson', 'D003', 'M003', 50000),

('E005', 'Eva Green', 'D002', 'M002', 70000);

-- 1. Count employees per department

SELECT DEPARTMENT_ID AS 'DEPARTMENT CODE',

COUNT(*) AS 'NO OF EMPLOYEES'

FROM DEPARTMENT

GROUP BY DEPARTMENT_ID;

-- 2. Sum of salary per department

SELECT DEPARTMENT_ID, SUM(SALARY) AS 'TOTAL SALARY'

FROM DEPARTMENT

GROUP BY DEPARTMENT_ID;

-- 3. Count and sum salary per department

SELECT DEPARTMENT_ID AS 'DEPARTMENT CODE',

COUNT(*) AS 'NO OF EMPLOYEES',

SUM(SALARY) AS 'TOTAL SALARY'

FROM DEPARTMENT

GROUP BY DEPARTMENT_ID;

-- 4. Total salary per department where manager_id = '103'

SELECT DEPARTMENT_ID AS 'DEPARTMENT CODE',

SUM(SALARY) AS 'TOTAL SALARY'

FROM DEPARTMENT

WHERE MANAGER_ID = '103'

GROUP BY DEPARTMENT_ID;

-- 5. Departments having more than 2 employees

SELECT DEPARTMENT_ID,

COUNT(*) AS 'NO OF EMPLOYEES'

FROM DEPARTMENT

GROUP BY DEPARTMENT_ID

HAVING COUNT(*) > 2;