CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);

INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('101', 'Alice', '123 Main St', '555-1234', 20),
('102', 'Bob', '456 Elm St', '555-5678', 22),
('103', 'Charlie', '789 Oak St', '555-8765', 21),
('104', 'David', '321 Pine St', '555-4321', 23);

SELECT * FROM SALESMAN;
SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE > 21 AND ADDRESS LIKE '%St';
SELECT * FROM STUDENT WHERE NAME LIKE 'A%';
SELECT * FROM STUDENT WHERE NAME = 'Alice' AND ADDRESS = '123 Main St';
SELECT * FROM STUDENT WHERE AGE = 23 AND (NAME = 'Bob' OR NAME = 'David');